language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
before_install:
    - pip install -U setuptools pip wheel
    - sudo apt-get update -qq
    - sudo apt-get install -qq libusb-dev libffi-dev libjpeg8-dev libudev-dev libusb-1.0-0-dev liblua5.2-dev
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
install:
    - pip install lupa --install-option='--no-luajit'
    - pip install flake8 pyflakes
    - pip install -e ".[web,hidtrigger,autorotate,chdkcamera]"
    - pip install -r test-requirements.txt
    - pip install -e .
script:
    - flake8 spreads spreadsplug tests --exclude=vendor
    - python -m pytest --cov spreads --cov spreadsplug -m "not guitest" tests
after_success: coveralls
